/**
 * Complying with Gui Library's license, I have made the following changes
 * to this class:
 * - Updated imports
 * - Updated version
 */
package com.mcf.davidee.guilib;

import java.util.Arrays;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

@Mod(modid = "guilib", name = "GUI Library", version = GuiLibrary.VERSION, acceptedMinecraftVersions = "[1.12.2]")
public class GuiLibrary {
	
	public static final String VERSION = "2.0.0.0";
	
	@EventHandler 
	public void preInit(FMLPreInitializationEvent event) {
		ModMetadata modMeta = event.getModMetadata();
		modMeta.authorList = Arrays.asList(new String[] { "Davidee" });
		modMeta.autogenerated = false;
		modMeta.credits = "Thanks to Mojang, Forge, and all your support.";
		modMeta.description = "A small library for creating minecraft GUIs.";
		modMeta.url = "http://www.minecraftforum.net/topic/1909236-/";
	}
	
}
